dataset: meta-mini-imagenet
train:
  split: meta-train
  image_size: 84
  normalization: True
  transform: flip
  n_batch: 200
  n_episode: 50
  n_way: 31
  n_shot: 1
  n_query: 15
val:
  split: meta-val
  image_size: 84
  normalization: True
  transform: flip
  n_batch: 200
  n_episode: 50
  n_way: 5
  n_shot: 1
  n_query: 15

encoder: resnet50
encoder_args:
  bn_args:
    track_running_stats: True
add: addneck
add_args:
  planes: 256

classifier: logistic

inner_args:
  reset_classifier: False
  n_step: 1
  encoder_lr: 0.000001 
  #0.00000001 
  #0.0000000001
  add_lr: 0.000001
  #0.00000001
  #0.0000000001
  classifier_lr: 0.000001
  #0.00000001
  #0.0000000001
  momentum: 0.9
  weight_decay: 5.e-4
  first_order: False

optimizer: sgd
optimizer_args:
  lr: 0.0005
  weight_decay: 5.e-4
  schedule: step
  milestones:
    - 100
    - 300
    - 450
    
load_pretrain: /userhome/root/workspace/zhangc/ours_barlow_cxr_31/save/resnet50_mini-imagenet/
re_pretrain: True
_parallel: True
pre_train: 60
meta_epochs: 0
fine_tune: 60

hnsw:
  dim: 256